import React from 'react';

export default function PrintableReport() {
  return (
    <div className="hidden print:block bg-white text-black p-12 font-serif leading-relaxed max-w-[210mm] mx-auto min-h-screen">
      {/* Header */}
      <div className="text-center border-b-2 border-black pb-8 mb-12">
        <h1 className="text-2xl font-bold uppercase mb-2">Vellore Institute of Technology</h1>
        <h2 className="text-xl font-semibold mb-2">School of Computer Science and Engineering</h2>
        <h3 className="text-lg mb-4">BCSE302L – Database Systems</h3>
        <div className="bg-black text-white inline-block px-4 py-1 font-bold uppercase tracking-widest text-sm">
          Project Report: Database Systems
        </div>
      </div>

      {/* Project Title */}
      <div className="mb-12">
        <h4 className="text-sm font-mono uppercase tracking-widest opacity-60 mb-2">Project Title</h4>
        <h2 className="text-4xl font-bold italic tracking-tight">SkyExplorer AI: Relational Database Astronomy</h2>
      </div>

      {/* Sections */}
      <div className="space-y-10">
        <section>
          <h3 className="text-lg font-bold uppercase border-b border-black mb-4">1. Problem Statement</h3>
          <p>
            The vast amount of data generated by astronomical surveys like the Sloan Digital Sky Survey (SDSS) is often inaccessible to students and amateur astronomers due to its technical complexity. Existing tools provide raw data (Right Ascension, Declination, Redshift) but lack intuitive interpretation. SkyExplorer AI aims to bridge this gap by creating a socially relevant educational platform that visualizes the cosmos and uses AI to synthesize raw database records into human-readable scientific insights.
          </p>
        </section>

        <section>
          <h3 className="text-lg font-bold uppercase border-b border-black mb-4">2. Literature Survey</h3>
          <p className="mb-4">
            <strong>Sloan Digital Sky Survey (SDSS):</strong> A major multi-spectral imaging and spectroscopic survey that has created the most detailed three-dimensional maps of the Universe.
          </p>
          <p className="mb-4">
            <strong>Aladin Lite API:</strong> A widely used tool for visualizing astronomical images in a web browser, developed by the Centre de Données astronomiques de Strasbourg (CDS).
          </p>
          <p>
            <strong>Relational Databases in Science:</strong> Research indicates that relational databases (SQL) are essential for maintaining data integrity and complex analytical joins in large-scale scientific datasets.
          </p>
        </section>

        <section>
          <h3 className="text-lg font-bold uppercase border-b border-black mb-4">3. Methodology & Database Design</h3>
          <div className="space-y-6">
            <div>
              <h4 className="font-bold mb-2">3.1 Relational Database Architecture</h4>
              <p>
                The system implements a robust relational strategy using <strong>Supabase (PostgreSQL)</strong>. This ensures ACID compliance and provides high-performance JSONB storage for complex astronomical metadata and AI-generated summaries.
              </p>
            </div>
            
            <div>
              <h4 className="font-bold mb-2">3.2 SQL Schema (PostgreSQL)</h4>
              <p className="font-mono text-sm bg-gray-100 p-4 rounded">
                Table: queries<br/>
                Fields: id (UUID), query_id (Text), ra (Float8), dec (Float8), catalog_data (JSONB), ai_summary (Text), created_at (Timestamp)
              </p>
            </div>

            <div>
              <h4 className="font-bold mb-2">3.3 Data Integrity & Security</h4>
              <p className="mb-2">The implementation leverages PostgreSQL's advanced features:</p>
              <ul className="list-disc ml-6 space-y-1">
                <li><strong>JSONB Indexing:</strong> Optimized retrieval of semi-structured catalog data.</li>
                <li><strong>Row Level Security (RLS):</strong> Granular access control for database operations.</li>
                <li><strong>ACID Compliance:</strong> Guarantees reliable transaction processing for scientific records.</li>
              </ul>
            </div>
          </div>
        </section>

        <section>
          <h3 className="text-lg font-bold uppercase border-b border-black mb-4">4. Implementation & Results</h3>
          <p className="mb-4">
            <strong>Intelligent Caching:</strong> The system reduces AI API costs and latency by implementing a persistent SQL cache. When a celestial object is queried, the system first checks the PostgreSQL database for existing records before invoking the Gemini AI engine.
          </p>
          <p>
            <strong>Social Impact:</strong> The platform democratizes access to astronomical data, allowing students to explore the universe without needing deep expertise in coordinate systems or raw data parsing.
          </p>
        </section>

        <section>
          <h3 className="text-lg font-bold uppercase border-b border-black mb-4">5. Conclusion</h3>
          <p>
            SkyExplorer AI successfully demonstrates how modern Relational Database Systems can be combined with Generative AI to solve educational challenges. By leveraging PostgreSQL's powerful indexing and relational integrity, the project makes the field of astronomy more accessible and innovative.
          </p>
        </section>
      </div>

      {/* Footer */}
      <div className="mt-20 pt-8 border-t border-black text-sm flex justify-between">
        <p>© 2026 SkyExplorer AI Project</p>
        <p>BCSE302L Database Systems</p>
      </div>
    </div>
  );
}
